FROM mnist-demo-pipeline-cicd

# Docker image for local development:
#  - interactive Jupyter setup
#  - running tests in watch mode (using entr)
#  - VS Code devcontainer

USER root
RUN apt-get install -y -qq --no-install-recommends entr jq
USER host_user

RUN : && \
    : Add py-percent format support for Jupyter notebooks, see && \
    : https://jupytext.readthedocs.io/en/latest/install.html && \
    jupyter nbextension install --py jupytext --user && \
    jupyter nbextension enable --py jupytext --user && \
    jupyter serverextension enable jupytext

# Jupyter server is only run in dev-mode
ARG JUPYTER_TOKEN
ENV JUPYTER_TOKEN=$JUPYTER_TOKEN
