# Docker image for testing and building pynb-dag-runner library
# Used by ci/cd (automated tests and build process) in Github.

FROM mnist-demo-pipeline-base

COPY docker/requirements.ci.txt /home/host_user/
RUN pip3 install --user -r /home/host_user/requirements.ci.txt

ENV MYPY_CACHE_DIR=/home/host_user/.cache/mypy
RUN mkdir -p $MYPY_CACHE_DIR

ENV PYTEST_ADDOPTS="-vvv -o cache_dir=/home/host_user/.cache/pytest"
