graph LR
    %% Mermaid input file for drawing task dependencies 
    %% See https://mermaid-js.github.io/mermaid
    %%
    TASK_SPAN_ID_0x2451ace4403aff24["ingest (Python task)"]
    TASK_SPAN_ID_0x4e710d6ae06eaaf9["eda (Jupytext task)"]
    TASK_SPAN_ID_0xe579d465d6a12c42["split_train_test (Python task)"]
    TASK_SPAN_ID_0xd00e22fd175cbfa0["train_model (Python task)"]
    TASK_SPAN_ID_0x556ac15d353ea822["train_model (Python task)"]
    TASK_SPAN_ID_0xe9d40dbd00eeffdf["train_model (Python task)"]
    TASK_SPAN_ID_0x0ebad3703990de1a["train_model (Python task)"]
    TASK_SPAN_ID_0xbca07ae4c6903055["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0x49296f4a16fbd628["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0x27b1365d31ce4b6f["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0xda95f06d49400c65["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0x017ed3d3019754ff["summary (Jupytext task)"]
    TASK_SPAN_ID_0x556ac15d353ea822 --> TASK_SPAN_ID_0x27b1365d31ce4b6f
    TASK_SPAN_ID_0x2451ace4403aff24 --> TASK_SPAN_ID_0xe579d465d6a12c42
    TASK_SPAN_ID_0xe579d465d6a12c42 --> TASK_SPAN_ID_0xe9d40dbd00eeffdf
    TASK_SPAN_ID_0xe579d465d6a12c42 --> TASK_SPAN_ID_0x0ebad3703990de1a
    TASK_SPAN_ID_0xe9d40dbd00eeffdf --> TASK_SPAN_ID_0x49296f4a16fbd628
    TASK_SPAN_ID_0xbca07ae4c6903055 --> TASK_SPAN_ID_0x017ed3d3019754ff
    TASK_SPAN_ID_0x2451ace4403aff24 --> TASK_SPAN_ID_0x4e710d6ae06eaaf9
    TASK_SPAN_ID_0x49296f4a16fbd628 --> TASK_SPAN_ID_0x017ed3d3019754ff
    TASK_SPAN_ID_0xd00e22fd175cbfa0 --> TASK_SPAN_ID_0xbca07ae4c6903055
    TASK_SPAN_ID_0xda95f06d49400c65 --> TASK_SPAN_ID_0x017ed3d3019754ff
    TASK_SPAN_ID_0xe579d465d6a12c42 --> TASK_SPAN_ID_0xd00e22fd175cbfa0
    TASK_SPAN_ID_0x27b1365d31ce4b6f --> TASK_SPAN_ID_0x017ed3d3019754ff
    TASK_SPAN_ID_0xe579d465d6a12c42 --> TASK_SPAN_ID_0x556ac15d353ea822
    TASK_SPAN_ID_0x0ebad3703990de1a --> TASK_SPAN_ID_0xda95f06d49400c65