graph LR
    %% Mermaid input file for drawing task dependencies 
    %% See https://mermaid-js.github.io/mermaid
    %%
    TASK_SPAN_ID_0x93efacc9426957b5["ingest (Python task)"]
    TASK_SPAN_ID_0xf530e1e3b37845ab["eda (Jupytext task)"]
    TASK_SPAN_ID_0xa095616c7af42a97["split_train_test (Python task)"]
    TASK_SPAN_ID_0x1ab6e374318842f9["train_model (Python task)"]
    TASK_SPAN_ID_0x67b3aef6bb543aa1["train_model (Python task)"]
    TASK_SPAN_ID_0x9e1fff6651f33625["train_model (Python task)"]
    TASK_SPAN_ID_0x98cc936e86770ff0["train_model (Python task)"]
    TASK_SPAN_ID_0x66542819cbfcc5de["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0x5e63589d2bd41797["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0xbcffa6526d9c9c3d["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0x62d86d6116eb9a83["benchmark-model (Jupytext task)"]
    TASK_SPAN_ID_0x9a3dd01f6340f8ec["summary (Jupytext task)"]
    TASK_SPAN_ID_0xa095616c7af42a97 --> TASK_SPAN_ID_0x98cc936e86770ff0
    TASK_SPAN_ID_0x66542819cbfcc5de --> TASK_SPAN_ID_0x9a3dd01f6340f8ec
    TASK_SPAN_ID_0xa095616c7af42a97 --> TASK_SPAN_ID_0x9e1fff6651f33625
    TASK_SPAN_ID_0x9e1fff6651f33625 --> TASK_SPAN_ID_0xbcffa6526d9c9c3d
    TASK_SPAN_ID_0x62d86d6116eb9a83 --> TASK_SPAN_ID_0x9a3dd01f6340f8ec
    TASK_SPAN_ID_0x98cc936e86770ff0 --> TASK_SPAN_ID_0x62d86d6116eb9a83
    TASK_SPAN_ID_0x93efacc9426957b5 --> TASK_SPAN_ID_0xa095616c7af42a97
    TASK_SPAN_ID_0x93efacc9426957b5 --> TASK_SPAN_ID_0xf530e1e3b37845ab
    TASK_SPAN_ID_0x67b3aef6bb543aa1 --> TASK_SPAN_ID_0x5e63589d2bd41797
    TASK_SPAN_ID_0xbcffa6526d9c9c3d --> TASK_SPAN_ID_0x9a3dd01f6340f8ec
    TASK_SPAN_ID_0xa095616c7af42a97 --> TASK_SPAN_ID_0x67b3aef6bb543aa1
    TASK_SPAN_ID_0x5e63589d2bd41797 --> TASK_SPAN_ID_0x9a3dd01f6340f8ec
    TASK_SPAN_ID_0x1ab6e374318842f9 --> TASK_SPAN_ID_0x66542819cbfcc5de
    TASK_SPAN_ID_0xa095616c7af42a97 --> TASK_SPAN_ID_0x1ab6e374318842f9